[tool.poetry]
name = "tink-homebank"
version = "0.0.1"
description = "Pull transactions from Tink and export them in a CSV for Homebank"
authors = ["José Ignacio Amelivia Santiago <ohcan2@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.8"
python-dotenv = "^1.0.0"
tink-http-python = "1.1.3"

[tool.poetry.group.dev.dependencies]
pytest = "^7.4.3"
pytest-cov = "^4.1.0"
pudb = "^2023.1"
codecov = "^2.1.13"
black = "^23.11.0"
pre-commit = "^3.5.0"
mock = "^5.1.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

