name: Build
on: [push, pull_request]
jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up production Docker Buildx
        if: startsWith(github.ref, 'refs/tags')
        id: production_builder
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        if: startsWith(github.ref, 'refs/tags')
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push production container
        if: startsWith(github.ref, 'refs/tags')
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          builder: ${{ steps.production_builder.outputs.name }}
          target: production
          tags: namelivia/tink-homebank:latest
